services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports: ["5000:5000"]
    environment:
      - JWT_SECRET_KEY=dev-secret-change-me
      - FLASK_APP=app:create_app
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    command: flask run --host=0.0.0.0 --port=5000 --debug

    volumes:
      - ./instance:/app/instance    
      - .:/app                     